<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.staitech</groupId>
        <artifactId>staitech-modules</artifactId>
        <version>2.6.0</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <artifactId>staitech-modules-anno</artifactId>

    <description>
        staitech-modules-anno图像标注系统模块
    </description>

    <dependencies>
        <!-- SpringCloud Alibaba Nacos -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Sentinel -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

        <!-- SpringBoot Actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-api-system</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-common-swagger</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-common-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-common-security</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http</artifactId>
            <version>4.1.68.Final</version> <!-- 请根据需要选择版本 -->
        </dependency>
        <!-- swagger增强版 -->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
            <version>2.0.9</version>
        </dependency>

        <dependency>
            <groupId>org.locationtech.jts</groupId>
            <artifactId>jts-core</artifactId>
            <version>1.19.0</version>
        </dependency>

        <dependency>
            <groupId>org.locationtech.jts</groupId>
            <artifactId>jts-ext</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/resources/lib/jts-ext-1.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.postgis</groupId>
            <artifactId>postgis-jdbc</artifactId>
            <version>2.5.0</version>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.5.0</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>3.3.2</version>
        </dependency>
        <dependency>
            <groupId>cn.staitech.log</groupId>
            <artifactId>log-audit-se-en-pacmvs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.baomidou</groupId>
                    <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>aliyun</id>
            <url>https://maven.aliyun.com/repository/public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>osgeo</id>
            <name>OSGeo Release Repository</name>
            <url>https://repo.osgeo.org/repository/release/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
        <repository>
            <id>osgeo-snapshot</id>
            <name>OSGeo Snapshot Repository</name>
            <url>https://repo.osgeo.org/repository/snapshot/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>


    <build>
        <finalName>${project.artifactId}</finalName>

        <resources>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <filtering>true</filtering>
                <excludes>
                    <exclude>**/*.jar</exclude>
                </excludes>
            </resource>
            <resource>
                <!--需要打包的jar路径-->
                <directory>${basedir}/src/main/resources/lib</directory>
                <filtering>false</filtering>
                <!--复制到的路径-->
                <targetPath>BOOT-INF/lib</targetPath>
                <includes>
                    <include>jts-ext-1.0.jar</include>
                </includes>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.6.2</version>
                <configuration>
                    <layout>ZIP</layout>
                    <includeSystemScope>true</includeSystemScope>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>docx</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <!--配置profiles环境-->
    <profiles>
        <profile>
            <!--开发环境-->
            <id>pacmvsdev</id>
            <properties>
                <activatedProperties>pacmvsdev</activatedProperties>
                <nacosNamespace>pacmvsdev</nacosNamespace>
                <nacosAddress>http://192.168.52.224/:8848</nacosAddress>
                <nacosGroup>DEFAULT_GROUP</nacosGroup>
                <serverAddr>192.168.52.224:8848</serverAddr>
            </properties>
        </profile>


        <profile>
            <!--测试环境-->
            <id>testpvcmvs</id>
            <properties>
                <activatedProperties>testpvcmvs</activatedProperties>
                <nacosNamespace>301f5c59-5f9c-451c-a77b-88d64ddfd9f0</nacosNamespace>
                <nacosAddress>http://192.168.160.105:8848</nacosAddress>
                <nacosGroup>DEFAULT_GROUP</nacosGroup>
                <serverAddr>192.168.160.105:8848</serverAddr>
            </properties>
        </profile>
        <profile>
            <!--生产环境-->
            <id>pathmedics</id>
            <properties>
                <activatedProperties>pathmedics</activatedProperties>
                <nacosNamespace>40438ad6-00f6-4524-8043-4e79819cccf0</nacosNamespace>
                <nacosAddress>http://10.10.4.13:8848</nacosAddress>
                <nacosGroup>DEFAULT_GROUP</nacosGroup>
                <serverAddr>10.10.4.13:8848</serverAddr>
            </properties>
        </profile>

    </profiles>
</project>
